name: Darren PRE Exporter
trigger: none
pr: none
parameters:
  - name: serviceConnectionExport
    displayName: Export from Service Connection
    type: string
    default: 'PowerPlatformTest'
    values:
      - 'PowerPlatformTest'
      - 'PowerPlatform'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
      - 'POWERAPPS-PRE-SDS-PROD'
  - name: exportToBranch
    displayName: Export To Branch
    type: string
    default: 'refactoring-tests'
  - name: serviceConnectionImport
    displayName: Import to Service Connection
    type: string
    default: 'PowerPlatformDev'
    values:
      - 'PowerPlatformDev'

variables:
  solutionName: dts_pre_recorded_evidence

pool:
  vmImage: windows-latest

steps:

  - checkout: self
    persistCredentials: true
    clean: true
  - task: NuGetCommand@2
    displayName: Install PAC
    inputs:
      command: 'custom'
      arguments: 'install Microsoft.PowerApps.CLI -OutputDirectory pac'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $pacNugetFolder = Get-ChildItem "pac" | Where-Object {$_.Name -match "Microsoft.PowerApps.CLI."}
        $pacPath = $pacNugetFolder.FullName + "\tools"
        echo "##vso[task.setvariable variable=pacPath]$pacPath"
  - task: PowerShell@2
    displayName: Add PacPath to Env Path
    inputs:
      targetType: 'inline'
      script: '$env:PATH = $env:PATH + ";" + "$(pacPath)"'
  - task: CmdLine@2
    inputs:
      script: 'set'
  - task: PowerPlatformToolInstaller@0
    inputs:
      DefaultVersion: true
  - task: PowerPlatformDownloadPaportal@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: 'PowerPlatformTest'
      Environment: 'https://orgd6d9527b.crm11.dynamics.com'
      DownloadPath: 'D:\a\1\s'
      WebsiteId: '682912fe-27db-452e-8aac-e938e6b99f57'
  
  - task: PowerPlatformExportSolution@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: ${{ parameters.serviceConnectionExport }}
      SolutionName: $(solutionName)
      SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
      AsyncOperation: false
      Managed: false
      MaxAsyncWaitTime: 120
      ExportAutoNumberingSettings: true
      ExportCalendarSettings: true
      ExportCustomizationSettings: true
      ExportEmailTrackingSettings: true
      ExportGeneralSettings: true
      ExportIsvConfig: true
      ExportMarketingSettings: true
      ExportOutlookSynchronizationSettings: true
      ExportRelationshipRoles: true
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dts_pre_recorded_evidence.zip'
      artifact: 'Solution Archive'
      publishLocation: 'pipeline'
  - task: PowerPlatformUnpackSolution@0
    inputs:
      SolutionInputFile: 'dts_pre_recorded_evidence.zip'
      SolutionTargetFolder: 'src'
  - task: CmdLine@2
    inputs:
      script: |
        echo Commit Power Platform Solution
        git config user.email "prebuildpipeline@hmcts.net"
        git config user.name "PRE Build Pipeline"
        git pull origin master
        git checkout -b ${{ parameters.exportToBranch }}
        git add --all
        git commit -m "Automatic solution commit"
        git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin ${{ parameters.exportToBranch }}
  #removed to speedup testing
  - task: PowerPlatformImportSolution@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: ${{ parameters.serviceConnectionImport }}
      SolutionInputFile: 'dts_pre_recorded_evidence.zip'
      AsyncOperation: true
      MaxAsyncWaitTime: '60'
