<<<<<<< HEAD
name: Darren PRE Exporter
trigger: none
pr: none
parameters:
  - name: serviceConnectionExport
    displayName: Export from Service Connection
    type: string
    default: 'PowerPlatformTest'
    values:
      - 'PowerPlatformTest'
      - 'PowerPlatform'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
      - 'POWERAPPS-PRE-SDS-PROD'
  - name: exportToBranch
    displayName: Export To Branch
    type: string
    default: 'refactoring-tests'
  - name: serviceConnectionImport
    displayName: Import to Service Connection
    type: string
    default: 'PowerPlatformDev'
    values:
      - 'PowerPlatformDev'
=======
---
name: Darren PRE Solution Deployment
trigger: none
pr: none
parameters:
  - name: serviceConnection
    displayName: Deploy to Service Connection
    type: string
    default: 'PowerPlatform'
    values:
      - 'PowerPlatform'
      - 'POWERAPPS-PRE-SBOX'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
#      - 'POWERAPPS-PRE-SDS-PROD'
  - name: deployFromBranch
    displayName: Deploy From Branch
    type: string
    default: 'ADO-Powerplatform'
>>>>>>> 61576e80ddaa29c4877d0c1c161644c7b4935f55

variables:
  solutionName: dts_pre_recorded_evidence

pool:
<<<<<<< HEAD
  vmImage: windows-latest

steps:

  - checkout: self
    persistCredentials: true
    clean: true
  - task: PowerPlatformToolInstaller@0
    inputs:
      DefaultVersion: true
  - task: PowerPlatformExportSolution@0
    inputs:
      authenticationType: 'PowerPlatformSPN'
      PowerPlatformSPN: ${{ parameters.serviceConnectionExport }}
      SolutionName: $(solutionName)
      SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
      AsyncOperation: false
      Managed: false
      MaxAsyncWaitTime: 120
      ExportAutoNumberingSettings: true
      ExportCalendarSettings: true
      ExportCustomizationSettings: true
      ExportEmailTrackingSettings: true
      ExportGeneralSettings: true
      ExportIsvConfig: true
      ExportMarketingSettings: true
      ExportOutlookSynchronizationSettings: true
      ExportRelationshipRoles: true
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dts_pre_recorded_evidence.zip'
      artifact: 'Solution Archive'
      publishLocation: 'pipeline'
  - task: PowerPlatformUnpackSolution@0
    inputs:
      SolutionInputFile: 'dts_pre_recorded_evidence.zip'
      SolutionTargetFolder: 'src'
  - task: CmdLine@2
    inputs:
      script: |
        echo Commit Power Platform Solution
        git config user.email "prebuildpipeline@hmcts.net"
        git config user.name "PRE Build Pipeline"
        git pull origin master
        git checkout -b ${{ parameters.exportToBranch }}
        git add --all
        git commit -m "Automatic solution commit"
        git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin ${{ parameters.exportToBranch }}
  #removed to speedup testing
  #- task: PowerPlatformImportSolution@0
  #  inputs:
  #    authenticationType: 'PowerPlatformSPN'
  #    PowerPlatformSPN: ${{ parameters.serviceConnectionExport }}
  #    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
  #    AsyncOperation: true
  #    MaxAsyncWaitTime: '60'
=======
  vmImage: 'windows-latest'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

>>>>>>> 61576e80ddaa29c4877d0c1c161644c7b4935f55
