name: Darren PRE Exporter
trigger: none
pr: none
parameters:
  - name: serviceConnection
    displayName: Import from Service Connection
    type: string
    default: 'PowerPlatform'
    values:
      - 'PowerPlatform'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
      - 'POWERAPPS-PRE-SDS-PROD'
  - name: exportToBranch
    displayName: Export To Branch
    type: string
    default: 'ADO-Powerplatform'

variables:
  solutionName: dts_pre_recorded_evidence

pool:
  vmImage: windows-latest

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        performMultiLevelLookup: true
    
    - task: NodeTool@0
      inputs:
        versionSpec: 18

    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'test\e2e'

    - task: CmdLine@2
      displayName: Add dotnet packages
      inputs:
        script: |
          dotnet add package Microsoft.Extensions.Configuration --version 6.0.0
          dotnet add package Microsoft.Extensions.Configuration.Json --version 6.0.0
          dotnet add package Microsoft.Playwright
          dotnet tool update --global PowerShell
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        workingDirectory: 'test\e2e'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        workingDirectory: 'test\e2e'
      
    - task: CmdLine@2
      inputs:
        script: 'npm i && npx playwright install'
        workingDirectory: 'test\e2e'
    
    - task: CmdLine@2
      displayName: npm playwright
      inputs:
        script: |
          npm i -D @playwright/test
        workingDirectory: 'D:\a\1\s\test\e2e'
    
    - task: CmdLine@2
      inputs:
        script: 'dotnet --version'
    - task: CmdLine@2
      inputs:
        script: 'dir D:\a\1\s\test\e2e'
    - task: CmdLine@2
      inputs:
        script: 'dir D:\a\1\s\test\e2e\bin\Debug\net6.0'
      
    - task: CmdLine@2
      inputs:
        script: 'pwsh D:\a\1\s\test\e2e\bin\Debug\net6.0\playwright.ps1 install'
  
    - task: CopyFiles@2
      displayName: Copy secrets.json
      inputs:
        SourceFolder: 'test\e2e'
        Contents: 'secrets.json'
        TargetFolder: 'D:\a\1\s\test\e2e\bin\Debug\net6.0'
        OverWrite: true
    - task: DownloadSecureFile@1
      name: authfile
      displayName: 'Download auth.json'
      inputs:
        secureFile: 'auth.json'
    - task: CmdLine@2
      displayName: Copy auth.json to net6.0 dir
      inputs:
        script: 'copy $(authfile.secureFilePath) D:\a\1\s\test\e2e\bin\Debug\net6.0'
    - task: CmdLine@2
      displayName: Copy auth.json to e2e dir
      inputs:
        script: 'copy $(authfile.secureFilePath) D:\a\1\s\test\e2e'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--filter AdminManageRecordings'
        testRunTitle: 'Run Tests'
        projects: 'D:\a\1\s\test\e2e\pre.csproj'

    - task: CmdLine@2
      inputs:
        script: 'more D:\a\_temp\*.trx'

    - task: CmdLine@2
      displayName: Create livingdoc
      inputs:
        script: 'livingdoc test-assembly bin/Debug/net6.0/pre.dll -t bin/Debug/net6.0/TestExecution.json'