---
name: PRE Solution Deployment
trigger: none
pr: none
parameters:
  - name: serviceConnection
    displayName: Deploy to Service Connection
    type: string
    default: 'POWERAPPS-PRE-SDS-STG'
    values:
      - 'POWERAPPS-PRE-SBOX'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
#      - 'POWERAPPS-PRE-SDS-PROD'
  - name: deployFromBranch
    displayName: Deploy From Branch
    type: string
    default: 'master'

variables:
  solutionName: dts_pre_recorded_evidence

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true
- task: PowerPlatformWhoAmi@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: ${{ parameters.serviceConnection }}

- task: CmdLine@2
  inputs:
    script: |
      echo Deploy Power Platform Solution
      git config user.email "prebuildpipeline@hmcts.net"
      git config user.name "PRE Build Pipeline"
      git checkout ${{ parameters.deployFromBranch }}

#- task: PowerPlatformCreateEnvironment@0
#  inputs:
#    authenticationType: 'PowerPlatformSPN'
#    PowerPlatformSPN: 'POWERAPPS-PRE-SDS-SBOX'
#    DisplayName: 'PRE Sandbox'
#    EnvironmentSku: 'Sandbox'
#    LocationName: 'unitedkingdom'
#    LanguageName: '1033'
#    CurrencyName: 'GBP'
#    DomainName: 'pre-sandbox'

- task: PowerPlatformPackSolution@0
  inputs:
    SolutionSourceFolder: 'src'
    SolutionType: Unmanaged
    SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'dts_pre_recorded_evidence.zip'
    artifact: 'Solution Archive'
    publishLocation: 'pipeline'

- task: CmdLine@2
  inputs:
    script: |
      cd test/e2e
      dotnet add package Microsoft.Extensions.Configuration --version 6.0.0
      dotnet add package Microsoft.Extensions.Configuration.Json --version 6.0.0
      dotnet add package Microsoft.Playwright
      dotnet tool update --global PowerShell
      pwsh playwright install

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: 'test/e2e'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    workingDirectory: 'test/e2e'

    #- task: PowerPlatformImportSolution@0
    #  inputs:
    #    authenticationType: 'PowerPlatformSPN'
    #    PowerPlatformSPN: ${{ parameters.serviceConnection }}
    #    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
    #    AsyncOperation: false
    #    OverwriteUnmanagedCustomizations: true
    #    SkipProductUpdateDependencies: true
    #    PublishWorkflows: true
